import React, { useState, useEffect } from 'react';
import { Sparkles, Check, X, ChevronRight, RefreshCw, Trophy, Home, FastForward } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { db } from '../firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';

export default function QuizTaker() {
    const [quizData, setQuizData] = useState([]);
    const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);
    const [selectedAnswer, setSelectedAnswer] = useState(null);
    const [isAnswerRevealed, setIsAnswerRevealed] = useState(false);
    const [score, setScore] = useState(0);
    const [quizComplete, setQuizComplete] = useState(false);

    const { userRole, currentUser } = useAuth();
    const navigate = useNavigate();

    useEffect(() => {
        // Scaffold logic: read passed quiz generated by backend
        const saved = localStorage.getItem('tempQuizData');
        if (saved) {
            setQuizData(JSON.parse(saved));
        } else {
            // no data, return home
            navigate(userRole === 'teacher' ? '/teacher-dashboard' : '/student-dashboard');
        }
    }, [navigate, userRole]);

    if (quizData.length === 0) {
        return (
            <div className="main-container">
                <div className="view-panel glass-panel" style={{ width: '100%', maxWidth: '700px', textAlign: 'center', padding: '3rem' }}>
                    <h2 className="title gradient-text" style={{ fontSize: '2rem' }}>Loading Quiz Data...</h2>
                    <p style={{ color: 'var(--text-muted)' }}>If this takes more than a few seconds, data may have been lost. Please generate the quiz again.</p>
                    <button className="btn-primary" style={{ marginTop: '2rem' }} onClick={() => navigate('/generate-quiz')}>
                        Return to Generator
                    </button>
                </div>
            </div>
        );
    }

    const currentQ = quizData[currentQuestionIdx];

    const handleOptionClick = (idx) => {
        if (isAnswerRevealed) return;
        setSelectedAnswer(idx);
        setIsAnswerRevealed(true);
        if (idx === currentQ.correctAnswer) {
            setScore(prev => prev + 1);
        }
    };

    const handleNextQuestion = () => {
        if (currentQuestionIdx < quizData.length - 1) {
            setCurrentQuestionIdx(prev => prev + 1);
            setSelectedAnswer(null);
            setIsAnswerRevealed(false);
        } else {
            setQuizComplete(true);
        }
    };

    const handleSkipQuestion = () => {
        if (currentQuestionIdx < quizData.length - 1) {
            setCurrentQuestionIdx(prev => prev + 1);
            setSelectedAnswer(null);
            setIsAnswerRevealed(false);
        } else {
            setQuizComplete(true);
        }
    };

    // Save score to Firestore when completed
    useEffect(() => {
        if (quizComplete && currentUser) {
            const saveScore = async () => {
                try {
                    await addDoc(collection(db, 'leaderboard'), {
                        userId: currentUser.uid,
                        userEmail: currentUser.email,
                        score: score,
                        total: quizData.length,
                        timestamp: serverTimestamp()
                    });
                } catch (e) {
                    console.error("Error saving score to leaderboard: ", e);
                }
            };
            saveScore();
        }
    }, [quizComplete, currentUser, score, quizData.length]);

    const handleRestart = () => {
        navigate('/generate-quiz');
    };

    if (quizComplete) {
        return (
            <div className="main-container">
                <div className="view-panel glass-panel result-container fadeIn">
                    <h2 className="title">Quiz Complete!</h2>

                    <div className="score-circle" style={{ '--score': (score / quizData.length) * 100 }}>
                        <div className="score-text">
                            {score}/{quizData.length}
                        </div>
                    </div>

                    <p className="result-feedback" style={{ marginBottom: '2rem' }}>
                        {score === quizData.length ?
                            "Perfect score! You're a true expert." :
                            score >= quizData.length / 2 ?
                                "Great job! You grasped most of the concepts." :
                                "Good effort! Might need a quick review."}
                    </p>

                    <div className="action-buttons" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', width: '100%' }}>
                        {userRole === 'student' && (
                            <Link to="/leaderboard" className="btn-primary" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', width: '100%', textDecoration: 'none' }}>
                                <Trophy size={18} /> View Leaderboard
                            </Link>
                        )}
                        <div style={{ display: 'flex', gap: '1rem' }}>
                            <button className="btn-secondary" onClick={handleRestart} style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                                <RefreshCw size={18} /> Create New Quiz
                            </button>
                            <Link to={userRole === 'teacher' ? '/teacher-dashboard' : '/student-dashboard'} className="btn-secondary" style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', textDecoration: 'none' }}>
                                <Home size={18} /> Dashboard
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="main-container">
            <div className="view-panel glass-panel quiz-container">
                <div className="quiz-header">
                    <div className="progress-indicator">
                        <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                            Question {currentQuestionIdx + 1} of {quizData.length}
                        </span>
                    </div>
                    <div className="progress-pills">
                        {quizData.map((_, idx) => (
                            <div
                                key={idx}
                                className={`pill ${idx === currentQuestionIdx ? 'active' : ''} ${idx < currentQuestionIdx ? 'completed' : ''}`}
                            ></div>
                        ))}
                    </div>
                </div>

                <h2 className="question-text">{currentQ.question}</h2>

                {/* Only rendering MCQ for simplicity in exact representation, but scalable */}
                <div className="options-container">
                    {currentQ.options && currentQ.options.map((option, idx) => {
                        const isCorrect = idx === currentQ.correctAnswer;
                        const isSelected = selectedAnswer === idx;

                        let optionClass = 'option-btn';
                        if (isAnswerRevealed) {
                            if (isSelected && isCorrect) optionClass += ' correct';
                            else if (isSelected && !isCorrect) optionClass += ' incorrect';
                            else if (isCorrect) optionClass += ' correct';
                        } else if (isSelected) {
                            optionClass += ' selected';
                        }

                        const letters = ['A', 'B', 'C', 'D', 'E', 'F'];

                        return (
                            <button
                                key={idx}
                                className={optionClass}
                                onClick={() => handleOptionClick(idx)}
                                disabled={isAnswerRevealed}
                            >
                                <span className="option-letter">{letters[idx]}</span>
                                <span style={{ flex: 1 }}>{option}</span>
                                {isAnswerRevealed && isCorrect && <Check size={20} className="status-icon" />}
                                {isAnswerRevealed && isSelected && !isCorrect && <X size={20} className="status-icon" />}
                            </button>
                        );
                    })}
                </div>

                {isAnswerRevealed && (
                    <div className="explanation-box" style={{ marginTop: '1.5rem', padding: '1.5rem', borderRadius: '12px', background: 'rgba(255,255,255,0.05)', borderLeft: '4px solid var(--accent-color)', animation: 'fadeIn 0.5s ease-out' }}>
                        <p style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'var(--accent-color)', fontWeight: '600' }}>
                            <Sparkles size={18} /> AI Explanation
                        </p>
                        <p style={{ color: 'var(--text-muted)', lineHeight: '1.5' }}>{currentQ.explanation}</p>
                    </div>
                )}

                <div style={{ marginTop: '2rem', display: 'flex', justifyContent: 'space-between' }}>
                    {!isAnswerRevealed ? (
                        <button
                            className="btn-secondary"
                            onClick={handleSkipQuestion}
                            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                        >
                            <FastForward size={20} /> Skip Question
                        </button>
                    ) : <div></div>}

                    <button
                        className="btn-primary"
                        onClick={handleNextQuestion}
                        disabled={!isAnswerRevealed}
                        style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                    >
                        {currentQuestionIdx < quizData.length - 1 ? 'Next Question' : 'Finish Quiz'}
                        <ChevronRight size={20} />
                    </button>
                </div>
            </div>
        </div>
    );
}
